name: Trigger auto deployment for cicd-ap-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cicd-ap-2-AutoDeployTrigger-222d7baa-4dac-47de-9a94-7753bd922df5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CICDAP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CICDAP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CICDAP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cicdreg2.azurecr.io
          registryUsername: ${{ secrets.CICDAP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CICDAP2_REGISTRY_PASSWORD }}
          containerAppName: cicd-ap-2
          resourceGroup: cici_rg
          imageToBuild: cicdreg2.azurecr.io/cicd-ap-2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


